apiVersion: apps/v1
kind: Deployment
metadata:
  name: tap30-ride-demand-mlops
  namespace: tap30
  labels:
    app: tap30-ride-demand-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tap30-ride-demand-mlops
  template:
    metadata:
      labels:
        app: tap30-ride-demand-mlops
    spec:
      containers:
      - name: tap30-ride-demand-mlops
        image: hamedmakian/tap30-ride-demandmlops:V1.0.0
        ports:
        - containerPort: 8080